### PR TITLE
create index.html

### PR DESCRIPTION
**Pull request by vmyronets**
[My page](https://vmyronets.github.io/my-project/)

### CODE REVIEW

**Comment by vmyronets** [comment]
[gh-pages](https://vmyronets.github.io/my-project/)

**Review by vmyronets — COMMENTED** [review]
[My page](https://vmyronets.github.io/my-project/)

**Comment by vmyronets** [comment]
[My page](https://vmyronets.github.io/my-project/)

**Comment by vmyronets** [comment]
[My page](https://vmyronets.github.io/my-project/)

**Comment by vmyronets** [comment]
[My page](https://vmyronets.github.io/my-project/)

**Comment by vmyronets** [comment]
[My page](https://vmyronets.github.io/my-project/)

**Review by pavlopro — APPROVED** [review]
GJ!

**Pull request merged**
